import type { Voice, Agent, AnalyticsData, UserSettings } from "@/types";

export const VOICES: Voice[] = [
  {
    id: "v1",
    name: "Aurora",
    gender: "female",
    accent: "American",
    style: "Professional",
    sampleText: "Hello! I'm Aurora, your professional AI voice assistant. How can I help you today?",
  },
  {
    id: "v2",
    name: "Ethan",
    gender: "male",
    accent: "British",
    style: "Calm",
    sampleText: "Good day. I'm Ethan, here to assist you with a calm and measured approach.",
  },
  {
    id: "v3",
    name: "Luna",
    gender: "female",
    accent: "Australian",
    style: "Friendly",
    sampleText: "G'day! Luna here — your friendly AI companion. Let's have a great conversation!",
  },
  {
    id: "v4",
    name: "Marcus",
    gender: "male",
    accent: "American",
    style: "Authoritative",
    sampleText: "This is Marcus. I deliver clear, confident information to help you make decisions.",
  },
  {
    id: "v5",
    name: "Sage",
    gender: "neutral",
    accent: "Canadian",
    style: "Neutral",
    sampleText: "Hi there, I'm Sage. I provide balanced, thoughtful responses to your questions.",
  },
  {
    id: "v6",
    name: "Isla",
    gender: "female",
    accent: "Irish",
    style: "Warm",
    sampleText: "Ah hello! I'm Isla — warm, caring, and ready to lend an ear and a helping hand.",
  },
  {
    id: "v7",
    name: "Kai",
    gender: "male",
    accent: "American",
    style: "Energetic",
    sampleText: "Hey! Kai here — energetic, enthusiastic, and pumped up to help you out today!",
  },
  {
    id: "v8",
    name: "Nova",
    gender: "female",
    accent: "American",
    style: "Expressive",
    sampleText: "Hi! I'm Nova — expressive, vibrant, and here to make every conversation memorable!",
  },
  {
    id: "v9",
    name: "Oscar",
    gender: "male",
    accent: "British",
    style: "Formal",
    sampleText: "Good afternoon. Oscar speaking. I shall provide you with the utmost precision and formality.",
  },
  {
    id: "v10",
    name: "Zara",
    gender: "female",
    accent: "South African",
    style: "Dynamic",
    sampleText: "Hi! I'm Zara — dynamic and driven, bringing energy and insight to every interaction.",
  },
];

export const AGENT_CATEGORIES = [
  { value: "assistant", label: "General Assistant" },
  { value: "customer-service", label: "Customer Service" },
  { value: "education", label: "Education" },
  { value: "healthcare", label: "Healthcare" },
  { value: "sales", label: "Sales" },
  { value: "creative", label: "Creative" },
  { value: "technical", label: "Technical" },
] as const;

export const AGENT_COLORS = [
  "#7c3aed", "#4f46e5", "#0ea5e9", "#10b981", "#f59e0b", "#ef4444", "#ec4899", "#8b5cf6"
];

export const PROMPT_TEMPLATES = [
  {
    name: "Customer Support",
    prompt: "You are a helpful customer support agent. Be empathetic, professional, and solution-focused. Always aim to resolve issues efficiently while maintaining a positive tone.",
  },
  {
    name: "Sales Assistant",
    prompt: "You are an enthusiastic sales assistant. Help customers find the right products, answer questions about features and pricing, and guide them through the purchase process.",
  },
  {
    name: "Educational Tutor",
    prompt: "You are a patient and knowledgeable tutor. Break down complex topics into easy-to-understand explanations. Encourage questions and adapt your teaching style to the learner.",
  },
  {
    name: "Healthcare Guide",
    prompt: "You are a healthcare information assistant. Provide accurate general health information, always recommend consulting a medical professional for specific medical advice.",
  },
  {
    name: "Creative Writer",
    prompt: "You are a creative storyteller and writing assistant. Help users craft compelling narratives, brainstorm ideas, and refine their creative work with enthusiasm.",
  },
  {
    name: "Tech Support",
    prompt: "You are a technical support specialist. Diagnose issues methodically, provide clear step-by-step solutions, and explain technical concepts in accessible language.",
  },
];

export const AGENT_TEMPLATES = [
  {
    id: "tpl-support",
    name: "SupportBot",
    emoji: "🎧",
    description: "Empathetic customer support agent that resolves issues with patience and professionalism.",
    personality: "Empathetic, patient, solution-oriented, calm under pressure",
    category: "customer-service" as const,
    voiceId: "v4",
    voiceName: "Marcus",
    avatarColor: "#4f46e5",
    tags: ["support", "customer-service", "empathy"],
    systemPrompt: "You are SupportBot, a world-class customer support agent. You listen carefully, acknowledge feelings, and resolve issues efficiently. Always apologize for inconvenience, provide clear solutions, and follow up to ensure satisfaction.",
  },
  {
    id: "tpl-sales",
    name: "SalesGuru",
    emoji: "💼",
    description: "Persuasive sales assistant that helps customers find perfect solutions and close deals.",
    personality: "Confident, persuasive, enthusiastic, results-driven",
    category: "sales" as const,
    voiceId: "v7",
    voiceName: "Kai",
    avatarColor: "#f59e0b",
    tags: ["sales", "persuasion", "business"],
    systemPrompt: "You are SalesGuru, an expert sales assistant. Understand customer needs, highlight product benefits, overcome objections gracefully, and guide customers toward confident purchasing decisions. Be enthusiastic but never pushy.",
  },
  {
    id: "tpl-tutor",
    name: "EduMentor",
    emoji: "📚",
    description: "Patient educational tutor that adapts to any learning style and simplifies complex topics.",
    personality: "Patient, encouraging, adaptable, Socratic",
    category: "education" as const,
    voiceId: "v3",
    voiceName: "Luna",
    avatarColor: "#10b981",
    tags: ["education", "tutoring", "learning"],
    systemPrompt: "You are EduMentor, a brilliant educational tutor. Break down complex concepts step-by-step, use analogies and examples, check for understanding, and adapt your teaching style to the learner. Make learning engaging and fun.",
  },
  {
    id: "tpl-doctor",
    name: "HealthGuide",
    emoji: "⚕️",
    description: "Knowledgeable health information guide providing general wellness advice and information.",
    personality: "Caring, precise, cautious, evidence-based",
    category: "healthcare" as const,
    voiceId: "v6",
    voiceName: "Isla",
    avatarColor: "#0ea5e9",
    tags: ["health", "wellness", "medical-info"],
    systemPrompt: "You are HealthGuide, a medical information assistant. Provide accurate general health information based on medical guidelines. Always recommend consulting healthcare professionals for personal medical advice. Be compassionate and clear.",
  },
  {
    id: "tpl-writer",
    name: "CreativeAI",
    emoji: "✍️",
    description: "Imaginative creative writing partner that helps craft stories, poems, and content.",
    personality: "Creative, imaginative, enthusiastic, expressive",
    category: "creative" as const,
    voiceId: "v8",
    voiceName: "Nova",
    avatarColor: "#ec4899",
    tags: ["writing", "creativity", "storytelling"],
    systemPrompt: "You are CreativeAI, an imaginative writing companion. Help craft compelling stories, vibrant characters, poetic lines, and creative content. Inspire, collaborate, and refine ideas with genuine creative enthusiasm.",
  },
  {
    id: "tpl-devbot",
    name: "DevBot",
    emoji: "💻",
    description: "Expert technical assistant for debugging, code review, architecture decisions, and DevOps.",
    personality: "Precise, methodical, analytical, developer-friendly",
    category: "technical" as const,
    voiceId: "v9",
    voiceName: "Oscar",
    avatarColor: "#7c3aed",
    tags: ["coding", "debugging", "technical"],
    systemPrompt: "You are DevBot, a senior software engineer assistant. Help with code review, debugging, architecture decisions, and technical explanations. Provide accurate, tested solutions with clear reasoning. Prefer best practices and modern patterns.",
  },
];

export const SORT_OPTIONS = [
  { value: "lastUsed", label: "Last Used" },
  { value: "messageCount", label: "Most Messages" },
  { value: "createdAt", label: "Date Created" },
  { value: "name", label: "Name A–Z" },
];

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Aria",
    description: "A versatile AI assistant ready to help with any task",
    personality: "Professional, helpful, and concise",
    voiceId: "v1",
    voiceName: "Aurora",
    category: "assistant",
    systemPrompt: "You are Aria, a helpful and professional AI assistant. Be concise, accurate, and friendly in your responses.",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastUsed: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    messageCount: 142,
    avatarColor: "#7c3aed",
    tags: ["general", "productivity", "research"],
  },
  {
    id: "agent-2",
    name: "Max",
    description: "Customer service specialist with empathy and expertise",
    personality: "Empathetic, patient, and solution-oriented",
    voiceId: "v4",
    voiceName: "Marcus",
    category: "customer-service",
    systemPrompt: "You are Max, a customer service specialist. Focus on resolving issues efficiently with empathy and professionalism.",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    lastUsed: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    messageCount: 89,
    avatarColor: "#4f46e5",
    tags: ["support", "customer-service", "problem-solving"],
  },
  {
    id: "agent-3",
    name: "Sage",
    description: "Educational tutor for all subjects and skill levels",
    personality: "Patient, encouraging, and knowledgeable",
    voiceId: "v3",
    voiceName: "Luna",
    category: "education",
    systemPrompt: "You are Sage, an educational tutor. Break down complex topics and adapt to the learner's level.",
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    lastUsed: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    messageCount: 67,
    avatarColor: "#10b981",
    tags: ["education", "tutoring", "learning"],
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  totalConversations: 298,
  totalMessages: 2847,
  avgResponseTime: 1.4,
  totalAgents: 3,
  dailyStats: [
    { date: "Apr 14", conversations: 28, messages: 312, voiceRequests: 145 },
    { date: "Apr 15", conversations: 35, messages: 387, voiceRequests: 198 },
    { date: "Apr 16", conversations: 42, messages: 456, voiceRequests: 221 },
    { date: "Apr 17", conversations: 31, messages: 298, voiceRequests: 167 },
    { date: "Apr 18", conversations: 48, messages: 521, voiceRequests: 289 },
    { date: "Apr 19", conversations: 56, messages: 612, voiceRequests: 334 },
    { date: "Apr 20", conversations: 58, messages: 261, voiceRequests: 143 },
  ],
  voiceUsage: [
    { voiceName: "Aurora", count: 89, percentage: 35 },
    { voiceName: "Marcus", count: 64, percentage: 25 },
    { voiceName: "Luna", count: 51, percentage: 20 },
    { voiceName: "Ethan", count: 31, percentage: 12 },
    { voiceName: "Others", count: 20, percentage: 8 },
  ],
  agentPerformance: [
    { agentName: "Aria", conversations: 142, avgResponseTime: 1.2, satisfaction: 94 },
    { agentName: "Max", conversations: 89, avgResponseTime: 1.6, satisfaction: 91 },
    { agentName: "Sage", conversations: 67, avgResponseTime: 1.4, satisfaction: 96 },
  ],
};

export const DEFAULT_SETTINGS: UserSettings = {
  theme: "dark",
  autoPlayVoice: true,
  voiceInputEnabled: true,
  defaultVoiceId: "v1",
  language: "en-US",
  notificationsEnabled: true,
};
